<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="38912" started-at="2019-07-14T06:54:25Z" finished-at="2019-07-14T06:55:04Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="38912" started-at="2019-07-14T06:54:25Z" finished-at="2019-07-14T06:55:04Z">
      <class name="com.qa.pgsys.testcases.HomePageTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.qa.pgsys.testcases.HomePageTest@19c0f4a]" name="setup" is-config="true" duration-ms="32096" started-at="2019-07-14T06:54:25Z" finished-at="2019-07-14T06:54:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="About_SubLinkTest()[pri:9, instance:com.qa.pgsys.testcases.HomePageTest@19c0f4a]" name="About_SubLinkTest" duration-ms="5298" started-at="2019-07-14T06:54:57Z" finished-at="2019-07-14T06:55:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at com.qa.pgsys.testcases.HomePageTest.About_SubLinkTest(HomePageTest.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- About_SubLinkTest -->
        <test-method status="PASS" signature="tearup()[pri:0, instance:com.qa.pgsys.testcases.HomePageTest@19c0f4a]" name="tearup" is-config="true" duration-ms="1363" started-at="2019-07-14T06:55:02Z" finished-at="2019-07-14T06:55:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearup -->
      </class> <!-- com.qa.pgsys.testcases.HomePageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
